name: Build, Push & Deploy

on:
  push:
    branches:
      - main  # Trigger on any push to main, regardless of what files changed
  workflow_dispatch: {} # Allows manual triggering from the GitHub UI


env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: observability-platform-app
  GRAFANA_ECR_REPOSITORY: observability-platform-grafana
  PROMETHEUS_ECR_REPOSITORY: observability-platform-prometheus
  # Suppresses the Node 20 runner warning message cleanly
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Required for OIDC: lets this job request a web identity token from GitHub
    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug secret length (safe - no value exposed)
        run: echo -n "${{ secrets.AWS_DEPLOY_ROLE_ARN }}" | wc -c

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: echo "image_tag=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Build and push app image
        working-directory: ./app
        run: |
          docker build \
            -t "${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}" .

          docker push \
            "${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}"

      - name: Build and push Grafana image
        working-directory: ./monitoring/grafana
        run: |
          docker build \
            -t "${{ steps.ecr-login.outputs.registry }}/${{ env.GRAFANA_ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}" .

          docker push \
            "${{ steps.ecr-login.outputs.registry }}/${{ env.GRAFANA_ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}"

      - name: Build and push Prometheus image
        working-directory: ./monitoring/prometheus
        run: |
          docker build \
            -t "${{ steps.ecr-login.outputs.registry }}/${{ env.PROMETHEUS_ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}" .

          docker push \
            "${{ steps.ecr-login.outputs.registry }}/${{ env.PROMETHEUS_ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}"

  terraform-apply:
    needs: build-and-push
    runs-on: ubuntu-latest
    # Required for OIDC: lets this job request a web identity token from GitHub
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
            -var="app_image_tag=${{ needs.build-and-push.outputs.image_tag }}" \
            -var="grafana_image_tag=${{ needs.build-and-push.outputs.image_tag }}" \
            -var="prometheus_image_tag=${{ needs.build-and-push.outputs.image_tag }}"